# run with "docker compose up -d"
version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=items
    ports:
      - "5432:5433"
  invoice:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:12345@postgres:5432/invoice_service_dev
      - SECRET_KEY_BASE=foobar
    ports:
      - "4000:4000"
